### ISSUE TITLE
Include pytorch library in python evaluator image

### ISSUE THREAD

**Issue by trangmei** [Coursemology/evaluator-images#32]
To include any version of pytorch library in python 3.7 and subsequent python autograding images.

Requested by Prof Kan Min Yen.

**Comment by knmnyn** [comment]
Yes, needed before recess week ideally.  Thanks!

**Comment by MartinStrobel** [comment]
I've created a [pull request](https://github.com/Coursemology/evaluator-images/pull/33). Just added two lines of code, hope that doesn't break anything.

**Comment by knmnyn** [comment]
Please help expedite if possible!

**Comment by cysjonathan** [comment]
closed by #35 #36
